source 'https://rubygems.org'

gem 'capybara', '~> 3.29'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
gem 'rspec'
gem 'cucumber', '5.0.0'
gem 'rake'
gem 'site_prism', '~>3.6'
gem 'pry'
gem 'webdriver-highlighter'
gem 'rspec-retry'